# -*- coding: utf-8 -*-
"""把 APP 的案例库导出成网页版可直接加载的 JS 数据。"""
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "APP" / "LiurenFocusDiviner" / "entry" / "src" / "main" / "resources" / "rawfile" / "ancient" / "case_gallery.json"
DST = ROOT / "UI" / "_data" / "ancient_case_gallery.js"


def main() -> None:
    cases = json.loads(io.open(str(SRC), "r", encoding="utf-8").read())
    out = "/* generated by _tools/export_case_gallery_web.py; do not edit by hand */\n"
    out += "window.ANCIENT_CASES=" + json.dumps(cases, ensure_ascii=False, indent=2) + ";\n"
    DST.parent.mkdir(parents=True, exist_ok=True)
    io.open(str(DST), "w", encoding="utf-8", newline="\n").write(out)
    print("exported", len(cases), "->", DST)


if __name__ == "__main__":
    main()
