# -*- coding: utf-8 -*-
"""把偶遇实盘（UI/_data/ouyu_cases.json）导出成网页版可直接加载的 JS 数据。

与 export_case_gallery_web.py 同纪律：JSON 是真源，JS 是生成物，不手改 JS。

用法：
    python _tools/export_ouyu_web.py
"""
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "UI" / "_data" / "ouyu_cases.json"
DST = ROOT / "UI" / "_data" / "ouyu_cases.js"

HEADER = """/* generated by _tools/export_ouyu_web.py; do not edit by hand
 *
 * 偶遇实盘（encounter）：无占类、无可抓用神的一类占法。
 * 体例与样张见 大六壬文档/案例剧情/偶遇之占-体例与首个实盘.md
 *
 * 与古籍案例（ANCIENT_CASES）的区别：
 *   ancient  = 古人断例：有原文、有原断与应验 → 取用神、判吉凶、揭古断
 *   encounter= 今人现场：无原断、只有象     → 不取用神、不判吉凶、末传即心念落点
 *
 * 盘面不入库：原型用 LiurenCore.buildChart({date,hourZhi,calData,yjAll}) 现场复算，
 * 故本文件只存「现场 + 取象链 + 锚点」，一行盘面数据都不存（避免与引擎漂移）。
 * 锚点字段与 case_story.json 同构（kind/ref/pos），可直接被原型的 anchorMatch 复用。
 */
"""


def main() -> None:
    raw = json.loads(io.open(str(SRC), "r", encoding="utf-8").read())
    cases = raw.get("cases", [])
    out = HEADER + "window.OUYU_CASES=" + json.dumps(cases, ensure_ascii=False, indent=2) + ";\n"
    io.open(str(DST), "w", encoding="utf-8", newline="\n").write(out)
    lanes = sum(len(c.get("lanes", [])) for c in cases)
    links = sum(len(l.get("chain", [])) for c in cases for l in c.get("lanes", []))
    anchors = sum(len(k.get("anchors", [])) for c in cases for l in c.get("lanes", []) for k in l.get("chain", []))
    print("exported %d case(s), %d lane(s), %d link(s), %d anchor(s) -> %s" % (len(cases), lanes, links, anchors, DST))


if __name__ == "__main__":
    main()
