# -*- coding: utf-8 -*-
"""把 APP 的案例剧情数据（case_story.json）导出成网页版可直接加载的 JS。"""
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "APP" / "LiurenFocusDiviner" / "entry" / "src" / "main" / "resources" / "rawfile" / "ancient" / "case_story.json"
DST = ROOT / "UI" / "_data" / "case_story.js"


def main() -> None:
    data = json.loads(io.open(str(SRC), "r", encoding="utf-8").read())
    stories = data.get("stories", {})
    out = "/* generated by _tools/export_case_story_web.py; do not edit by hand */\n"
    out += "window.CASE_STORY=" + json.dumps(stories, ensure_ascii=False, indent=2) + ";\n"
    DST.parent.mkdir(parents=True, exist_ok=True)
    io.open(str(DST), "w", encoding="utf-8", newline="\n").write(out)
    asks = sum(len(v.get("asks", [])) for v in stories.values())
    print("exported", len(stories), "stories /", asks, "asks ->", DST)


if __name__ == "__main__":
    main()
