/* generated by _tools/export_case_gallery_web.py; do not edit by hand */
window.ANCIENT_CASES=[
  {
    "id": "xu_cibin_laiyi_jiazi",
    "title": "徐次宾占来意：七月甲子日午将申时",
    "source": "古籍案例鉴赏",
    "chapter": "占来意",
    "input": {
      "mj": "午",
      "dg": "甲",
      "dz": "子",
      "hour": "申",
      "monthZhi": "申"
    },
    "expect": {
      "kegs": [
        "子/甲",
        "戌/子",
        "戌/子",
        "申/戌"
      ],
      "chuans": [
        "戌",
        "申",
        "午"
      ],
      "chuanGz": [
        "甲戌",
        "壬申",
        "庚午"
      ],
      "chuanJiang": [
        "玄武",
        "白虎",
        "青龙"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "死",
      "monthZhi": "申",
      "method": "涉害",
      "zhonghuang": {
        "shiGan": "壬",
        "bianGan": "戊",
        "bianGong": "申",
        "bianLq": "妻财",
        "bianInChuan": "中传"
      }
    },
    "original": "来意因西南上，紧速追捕一盗，坠马折伤右足，感风七日而殒。",
    "summary": "以申时先锋门立太极：申为西南、传送、七月旺金，又乘白虎入中传；初传戌为甲木之财而乘玄武，故事起追捕盗贼。末传午火休囚不救，甲木秋死遇旺金，故应七日。",
    "chain": [
      "先锋门：申时主外动、急迫；七月申金当令，甲木死而被旺金所克。",
      "事类：初传戌为日干之财，乘玄武为盗贼，故知因盗起事。",
      "过程：中传申为传送乘白虎，主道路追捕、金刃伤灾；戌为足临日支之侧，古断取伤右足。",
      "转归：末传午为胜光火，七月囚死，不能制金救木。",
      "应期：申数七；至第七日庚午，庚金再克甲木而午火休囚不救，故曰七日殒。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "routes": [
      "base",
      "duxiang",
      "zhonghuang",
      "yongshen",
      "bifa"
    ],
    "focus": {
      "hour": "申",
      "yongShen": "申",
      "chuan": [
        "戌",
        "申",
        "午"
      ],
      "bianGong": "申"
    },
    "reasoning": [
      {
        "claim": "来意因西南上紧速追捕一盗",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "hour",
            "ref": "申",
            "why": "申为先锋门，主事发之端与急动"
          },
          {
            "view": "base",
            "kind": "gong",
            "ref": "申",
            "why": "申方属西南，古断以时支方应来意之地"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "戌",
            "why": "戌为日干甲木之财，事端起于财"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "戌/玄武",
            "why": "玄武主盗贼暗昧，财乘玄武故为盗"
          }
        ],
        "ruleRef": "先锋门取象；玄武类神；六亲取财",
        "note": "时支定方与急，初传财乘玄武定“盗”之事实。",
        "role": "main"
      },
      {
        "claim": "坠马折伤右足",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "申",
            "why": "申为传送道路，又乘白虎主金刃伤动"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "申/白虎",
            "why": "白虎主伤灾、道路刑杀"
          },
          {
            "view": "base",
            "kind": "zhi",
            "ref": "戌",
            "why": "戌为足；戌临日辰之侧，古断取伤右足"
          }
        ],
        "ruleRef": "白虎/传送类神；支辰身体取象",
        "note": "道路、白虎、日马与足象同见，故成坠马折足之链。",
        "role": "support"
      },
      {
        "claim": "感风七日而殒",
        "route": "zhonghuang",
        "evidence": [
          {
            "view": "zhonghuang",
            "kind": "shiGan",
            "ref": "壬",
            "why": "申时时干为壬，先锋门立太极"
          },
          {
            "view": "zhonghuang",
            "kind": "bianGan",
            "ref": "戊",
            "why": "中黄五变，壬变戊，落申宫"
          },
          {
            "view": "base",
            "kind": "wuxing",
            "ref": "甲木秋死/申金旺",
            "why": "七月甲木死，申金旺而克木"
          },
          {
            "view": "base",
            "kind": "shu",
            "ref": "申数七",
            "why": "古以申数七，至庚午日金再克木而火囚不救"
          }
        ],
        "ruleRef": "中黄时干变干；旺衰休囚；支数应期",
        "note": "中黄见变干戊落申宫带财象，参证事端；生死应期仍以旺衰与支数为主。",
        "role": "cross"
      }
    ],
    "topics": [
      "来意"
    ]
  },
  {
    "id": "zhonghuang_c1_shen_body",
    "title": "释己身第一：十一月丑将丙寅日戌时",
    "source": "中黄五变经",
    "chapter": "释己身第一",
    "input": {
      "mj": "丑",
      "dg": "丙",
      "dz": "寅",
      "hour": "戌",
      "monthZhi": "子"
    },
    "expect": {
      "kegs": [
        "申/丙",
        "亥/申",
        "巳/寅",
        "申/巳"
      ],
      "chuans": [
        "申",
        "亥",
        "寅"
      ],
      "chuanGz": [
        "丙申",
        "己亥",
        "庚寅"
      ],
      "chuanJiang": [
        "天后",
        "朱雀",
        "青龙"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "囚",
      "monthZhi": "子",
      "method": "涉害",
      "zhonghuang": {
        "shiGan": "戊",
        "bianGan": "壬",
        "bianGong": "戌",
        "bianLq": "官鬼",
        "bianInChuan": ""
      }
    },
    "original": "课体涉害，三传申亥寅。驿马乘天后临身，朱雀入关，青龙入末。",
    "summary": "己身以干上申为动象，初传申乘天后主身动而有私门之事；中传亥乘朱雀主音信文书；末传寅乘青龙为解神，终归有解。",
    "chain": [
      "课体：涉害课，事从艰难中出。",
      "事类：干上申为驿马，临丙干，身动之象。",
      "天将：初传天后、中传朱雀、末传青龙，先私后文书，终得青龙之解。",
      "盘态：丙寅日子月，日干囚；旬空戌亥，中传亥空，音信先虚后实。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "topics": [
      "己身"
    ]
  },
  {
    "id": "zhonghuang_c8_1_fuguan_zhengui",
    "title": "释复建真鬼：十一月将庚子日申时",
    "source": "中黄五变经",
    "chapter": "释复建真鬼",
    "input": {
      "mj": "子",
      "dg": "庚",
      "dz": "子",
      "hour": "申",
      "monthZhi": "亥"
    },
    "expect": {
      "kegs": [
        "子/庚",
        "辰/子",
        "辰/子",
        "申/辰"
      ],
      "chuans": [
        "辰",
        "申",
        "子"
      ],
      "chuanGz": [
        "庚辰",
        "甲申",
        "丙子"
      ],
      "chuanJiang": [
        "六合",
        "白虎",
        "天后"
      ],
      "xunkong": [
        "辰",
        "巳"
      ],
      "dayWangShuai": "囚",
      "monthZhi": "亥",
      "method": "涉害",
      "zhonghuang": {
        "shiGan": "甲",
        "bianGan": "壬",
        "bianGong": "申",
        "bianLq": "子孙",
        "bianInChuan": "中传"
      }
    },
    "original": "三传辰申子，初传六合临辰，中传白虎临申，末传天后临子。",
    "summary": "复建真鬼以辰为初传，辰戌丑未为墓地结绝；中传申乘白虎为刑杀动象，末传子乘天后为润下，先合后战，终归阴私。",
    "chain": [
      "课体：涉害，事由逼近而成。",
      "事类：初传辰为墓地，乘六合，主结交中藏结绝。",
      "过程：中传申乘白虎，金气刑杀，动中见战。",
      "转归：末传子乘天后，水局润下，事归阴私隐秘。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "topics": [
      "复建"
    ]
  },
  {
    "id": "zhonghuang_c10_5_guansong",
    "title": "释官讼门：壬子人十一月将癸卯日卯时",
    "source": "中黄五变经",
    "chapter": "释官讼门",
    "input": {
      "mj": "子",
      "dg": "癸",
      "dz": "卯",
      "hour": "卯",
      "yearGan": "壬",
      "yearZhi": "子",
      "monthZhi": "亥"
    },
    "expect": {
      "kegs": [
        "戌/癸",
        "未/戌",
        "子/卯",
        "酉/子"
      ],
      "chuans": [
        "戌",
        "未",
        "辰"
      ],
      "chuanGz": [
        "壬戌",
        "己未",
        "丙辰"
      ],
      "chuanJiang": [
        "青龙",
        "朱雀",
        "天后"
      ],
      "xunkong": [
        "辰",
        "巳"
      ],
      "dayWangShuai": "旺",
      "monthZhi": "亥",
      "method": "元首",
      "zhonghuang": {
        "shiGan": "乙",
        "bianGan": "己",
        "bianGong": "卯",
        "bianLq": "官鬼",
        "bianInChuan": ""
      }
    },
    "original": "元首课，三传戌未辰。初传青龙临戌，中传朱雀临未，末传天后临辰。",
    "summary": "官讼以朱雀为口舌文书，入中传而未土；初传戌乘青龙主事端有名分之争，末传辰乘天后而旬空，讼势虽起而终陷虚空。",
    "chain": [
      "课体：元首，事由上起，名分先立。",
      "事类：中传朱雀临未，文书口舌进入事中。",
      "转归：末传辰旬空，乘天后，官讼终归虚耗。",
      "盘态：癸日子月旺，能任其争；辰巳空，末传落空。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "topics": [
      "官讼"
    ]
  },
  {
    "id": "zhonghuang_c12_1_wangdao",
    "title": "释占亡盗门：乙亥生人十一月将乙未日卯时",
    "source": "中黄五变经",
    "chapter": "释占亡盗门",
    "input": {
      "mj": "子",
      "dg": "乙",
      "dz": "未",
      "hour": "卯",
      "yearGan": "乙",
      "yearZhi": "亥",
      "monthZhi": "亥"
    },
    "expect": {
      "kegs": [
        "丑/乙",
        "戌/丑",
        "辰/未",
        "丑/辰"
      ],
      "chuans": [
        "丑",
        "戌",
        "未"
      ],
      "chuanGz": [
        "丁丑",
        "丙戌",
        "癸未"
      ],
      "chuanJiang": [
        "螣蛇",
        "太阴",
        "白虎"
      ],
      "xunkong": [
        "辰",
        "巳"
      ],
      "dayWangShuai": "相",
      "monthZhi": "亥",
      "method": "重审",
      "zhonghuang": {
        "shiGan": "己",
        "bianGan": "丁",
        "bianGong": "卯",
        "bianLq": "子孙",
        "bianInChuan": ""
      }
    },
    "original": "重审课，三传丑戌未。初传螣蛇临丑，中传太阴临戌，末传白虎临未。",
    "summary": "亡盗取玄武类神不现，而见太阴、白虎分守中末；丑戌未三传相刑，主失物因内部刑害而起，终见肃杀。",
    "chain": [
      "课体：重审，事多反覆审度。",
      "事类：初传丑乘螣蛇，虚惊暗昧；中传戌乘太阴，阴私藏匿。",
      "转归：末传未乘白虎，肃杀见伤，失脱难全。",
      "盘态：乙日子月相，辰巳空，支上辰空，藏处不实。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "topics": [
      "亡盗"
    ]
  },
  {
    "id": "zhonghuang_c14_1_yuanxing",
    "title": "释占远行近出：癸丑生人行年丁亥十一月将甲午日寅时",
    "source": "中黄五变经",
    "chapter": "释占远行近出",
    "input": {
      "mj": "子",
      "dg": "甲",
      "dz": "午",
      "hour": "寅",
      "yearGan": "癸",
      "yearZhi": "丑",
      "monthZhi": "亥"
    },
    "expect": {
      "kegs": [
        "子/甲",
        "戌/子",
        "辰/午",
        "寅/辰"
      ],
      "chuans": [
        "戌",
        "申",
        "午"
      ],
      "chuanGz": [
        "甲戌",
        "壬申",
        "庚午"
      ],
      "chuanJiang": [
        "六合",
        "螣蛇",
        "天后"
      ],
      "xunkong": [
        "辰",
        "巳"
      ],
      "dayWangShuai": "相",
      "monthZhi": "亥",
      "method": "涉害",
      "zhonghuang": {
        "shiGan": "丙",
        "bianGan": "庚",
        "bianGong": "寅",
        "bianLq": "官鬼",
        "bianInChuan": ""
      }
    },
    "original": "三传戌申午，初传六合临戌，中传螣蛇临申，末传天后临午。",
    "summary": "远行看道路与驿马：初传戌乘六合主出行有伴，中传申乘螣蛇主道路虚惊，末传午乘天后主归处阴私；申子辰水局暗动，行而有阻。",
    "chain": [
      "课体：涉害，行途多阻。",
      "事类：初传戌为足，乘六合，出行结伴。",
      "过程：中传申为道路，乘螣蛇，途中虚惊缠绕。",
      "转归：末传午乘天后，归处近水阴私。",
      "盘态：甲午日子月相，辰巳空，支上午上辰空，行期多改。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "topics": [
      "远行"
    ]
  },
  {
    "id": "renzhan_jiazi_006_shao_shengshi",
    "title": "邵彦和占省试：九月甲子日卯将寅时",
    "source": "壬占汇选·卷之一",
    "chapter": "占验006 邵占省试",
    "input": {
      "mj": "卯",
      "dg": "甲",
      "dz": "子",
      "hour": "寅",
      "yearGan": "己",
      "yearZhi": "酉",
      "monthZhi": "戌"
    },
    "expect": {
      "kegs": [
        "卯/甲",
        "辰/卯",
        "丑/子",
        "寅/丑"
      ],
      "chuans": [
        "辰",
        "巳",
        "午"
      ],
      "chuanGz": [
        "戊辰",
        "己巳",
        "庚午"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "囚",
      "monthZhi": "戌",
      "method": "比用",
      "zhonghuang": {
        "shiGan": "丙",
        "bianGan": "庚",
        "bianGong": "寅",
        "bianLq": "官鬼",
        "bianInChuan": ""
      }
    },
    "original": "谢省元三次到场屋，今次又不得；行年亥加戌，长生学堂空而加空，宅上日贵作天空，不过虚名文学；中末巳午火脱干，午主心病见蛇。",
    "summary": "程序复算得四课卯甲/辰卯/丑子/寅丑，三传辰巳午，比用发用。甲木九月囚，中末巳午泄木，古断以“脱干、学堂空、贵作天空”看文名虚耗；结构与占验原文可互参。",
    "chain": [
      "课体：比用，事从同类相干处取用。",
      "事类：三传辰巳午连茹向火，甲木被泄，古断谓文气外脱。",
      "年命：乙丑生，行年亥加戌；戌亥旬空，古断取“长生学堂空而加空”。",
      "盘态：甲子日九月，日干囚；戌亥空，贵人/学堂诸象易落虚名。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "routes": [
      "base",
      "duxiang",
      "zhonghuang",
      "bifa"
    ],
    "focus": {
      "hour": "寅",
      "yongShen": "午",
      "chuan": [
        "辰",
        "巳",
        "午"
      ],
      "bianGong": "寅"
    },
    "reasoning": [
      {
        "claim": "今次又不得，文名多虚",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "囚",
            "why": "甲木九月囚，文气根力不足"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "巳",
            "why": "巳火泄木，文气外脱"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "午",
            "why": "午火再泄，古断以脱干看文名难成"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌亥旬空，学堂贵人诸象易落虚名"
          }
        ],
        "ruleRef": "旺衰休囚；火脱木象；旬空",
        "note": "本链只取课传与空亡可复核部分。",
        "role": "main"
      },
      {
        "claim": "更五次不遂，不免文学中心病",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "巳",
            "why": "巳为火，脱干而近心象"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "午",
            "why": "午主心，火脱太过，古断因言心病"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "亥",
            "why": "亥为空，古断“空而加空”多主虚名难实"
          }
        ],
        "ruleRef": "支辰身体/脏腑取象；旬空",
        "note": "“心病”属古籍断语记录，现代不作医疗判断。",
        "role": "risk"
      },
      {
        "claim": "行年亥加戌一句，程序口径存疑",
        "route": "base",
        "evidence": [
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "本盘戌亥旬空，与原文“空而加空”相应"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "亥",
            "why": "同上，亥空可锚"
          },
          {
            "view": "zhonghuang",
            "kind": "bianGong",
            "ref": "寅",
            "why": "中黄变干庚落寅宫，仅作旁证，不主行年"
          }
        ],
        "ruleRef": "旬空；中黄变干落宫",
        "note": "原文“行年上亥加戌”与程序本命起数结果不完全一致，入库时标为传本/起法差异，不强合。",
        "role": "support"
      }
    ],
    "topics": [
      "省试"
    ]
  },
  {
    "id": "renzhan_jiazi_011_xue_xingren",
    "title": "雪心占行人：十月甲子日卯将子时",
    "source": "壬占汇选·卷之一",
    "chapter": "占验011 雪占行人",
    "input": {
      "mj": "卯",
      "dg": "甲",
      "dz": "子",
      "hour": "子",
      "yearGan": "乙",
      "yearZhi": "卯",
      "monthZhi": "亥"
    },
    "expect": {
      "kegs": [
        "巳/甲",
        "申/巳",
        "卯/子",
        "午/卯"
      ],
      "chuans": [
        "申",
        "亥",
        "寅"
      ],
      "chuanGz": [
        "壬申",
        "乙亥",
        "丙寅"
      ],
      "chuanJiang": [
        "螣蛇",
        "勾陈",
        "白虎"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "相",
      "monthZhi": "亥",
      "method": "重审",
      "zhonghuang": {
        "shiGan": "甲",
        "bianGan": "甲",
        "bianGong": "子",
        "bianLq": "比肩",
        "bianInChuan": ""
      }
    },
    "original": "占行人，责元武及末传。今元武在辰加丑，末传寅为马，当主来。果于十一月十四癸巳日大雪归。",
    "summary": "程序复算三传申亥寅，重审课。古断行人取末传寅为马、以元武方位察踪迹；中传亥空而末传寅马引动，主迟而后至。",
    "chain": [
      "课体：重审，行人消息反覆而后定。",
      "事类：末传寅为驿马之象，古断以末传马主归动。",
      "盘态：甲子日十月，日干相；戌亥空，中传亥空，音信先虚。",
      "应期：原文应癸巳日大雪归，属古案应期记录，仅作文献参照。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "routes": [
      "base",
      "duxiang",
      "yongshen"
    ],
    "focus": {
      "hour": "子",
      "yongShen": "寅",
      "chuan": [
        "申",
        "亥",
        "寅"
      ],
      "bianGong": "子"
    },
    "reasoning": [
      {
        "claim": "占行人主来而迟",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "寅",
            "why": "末传寅为马，古断行人以末传马动主归",
            "mark": "马",
            "key": true
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "亥",
            "why": "中传亥空，音信与行期先虚后实",
            "mark": "空",
            "key": true
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "亥",
            "why": "亥在旬空，故应期有迟"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "相",
            "why": "甲木十月相，事虽迟而终有气"
          }
        ],
        "ruleRef": "末传马；旬空；旺衰",
        "note": "应期“癸巳日大雪归”为原案记录，仅作文献参照。",
        "role": "main"
      },
      {
        "claim": "行人链条宜抓用神看",
        "route": "yongshen",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "申",
            "why": "申为道路行人之象，事起在路"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "寅",
            "why": "归看末传，寅马动故主来",
            "mark": "马",
            "key": true
          },
          {
            "view": "base",
            "kind": "keg",
            "ref": "午/卯",
            "why": "第四课午/卯，木火相生，事势不绝"
          }
        ],
        "ruleRef": "行人类证取用；动态三传",
        "note": "此案的讲解重点应放在“何以取末传马”，而非只给“当主来”。",
        "role": "support"
      }
    ],
    "topics": [
      "行人"
    ]
  },
  {
    "id": "renzhan_jiazi_013_shao_liunian",
    "title": "邵彦和占流年：二月甲子日亥将午时",
    "source": "壬占汇选·卷之一",
    "chapter": "占验013 邵占流年",
    "input": {
      "mj": "亥",
      "dg": "甲",
      "dz": "子",
      "hour": "午",
      "yearGan": "戊",
      "yearZhi": "申",
      "monthZhi": "卯"
    },
    "expect": {
      "kegs": [
        "未/甲",
        "子/未",
        "巳/子",
        "戌/巳"
      ],
      "chuans": [
        "子",
        "巳",
        "戌"
      ],
      "chuanGz": [
        "甲子",
        "己巳",
        "甲戌"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "旺",
      "monthZhi": "卯",
      "method": "比用",
      "zhonghuang": {
        "shiGan": "庚",
        "bianGan": "壬",
        "bianGong": "午",
        "bianLq": "父母",
        "bianInChuan": ""
      }
    },
    "original": "岁内眷属人来，必成大狱；天罡加日本名天狱。破碎作太常入宅，主有丧服人归来分挠争屋；末后须添一口，又见分灶。",
    "summary": "程序复算三传子巳戌，比用课。古断以未加甲为墓、子未相害、戌亥空劫与破碎入宅，推演眷属争产兴讼；此处只取课传结构复核，不作现实断语。",
    "chain": [
      "课体：比用，事与同气相争。",
      "事类：干上未为木墓，古断谓眷属入宅相挠。",
      "盘态：甲子日二月，日干旺；戌亥空，末传戌空，事绪久缠而多虚耗。",
      "结构：三传子巳戌，由印绶而火土，古断以害、墓、破碎串成家宅狱讼之象。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "午",
      "yongShen": "未",
      "chuan": [
        "子",
        "巳",
        "戌"
      ],
      "bianGong": "午"
    },
    "reasoning": [
      {
        "claim": "岁内眷属人来，必成大狱",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "keg",
            "ref": "未/甲",
            "why": "干上未为木墓，古断以墓临干主眷属纠缠"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "子",
            "why": "子与未害，事端由害起"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "旺",
            "why": "甲木二月旺，能任其事，故狱讼成大而非即溃"
          }
        ],
        "ruleRef": "墓神临干；子未相害；旺衰",
        "note": "官讼之象为古籍断法整理，不构成现实法律判断。",
        "role": "main"
      },
      {
        "claim": "分挠争屋、末后添口分灶",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "巳",
            "why": "巳为厨灶之象，古断牵及分灶"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "戌",
            "why": "末传戌空，事尾多虚耗反复"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌在旬空，末传落空，争产久缠"
          }
        ],
        "ruleRef": "支辰物类；旬空",
        "note": "“添口/分灶”取象链条较长，展示时应标为古案象法。",
        "role": "risk"
      }
    ],
    "topics": [
      "流年",
      "官讼"
    ]
  },
  {
    "id": "renzhan_jiazi_016_shao_yibing",
    "title": "邵彦和占医病：九月甲子日卯将申时",
    "source": "壬占汇选·卷之一",
    "chapter": "占验016 邵占医病",
    "input": {
      "mj": "卯",
      "dg": "甲",
      "dz": "子",
      "hour": "申",
      "yearGan": "己",
      "yearZhi": "酉",
      "monthZhi": "戌"
    },
    "expect": {
      "kegs": [
        "酉/甲",
        "辰/酉",
        "未/子",
        "寅/未"
      ],
      "chuans": [
        "寅",
        "酉",
        "辰"
      ],
      "chuanGz": [
        "丙寅",
        "癸酉",
        "戊辰"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "囚",
      "monthZhi": "戌",
      "method": "比用",
      "zhonghuang": {
        "shiGan": "壬",
        "bianGan": "戊",
        "bianGong": "申",
        "bianLq": "妻财",
        "bianInChuan": ""
      }
    },
    "original": "此病因往妻家有私情、失情人所赠之物，思虑而得病；酉为色作勾陈，辰为脾为肌肤，加酉败气，思虑伤脾，肌肤消瘦。",
    "summary": "程序复算三传寅酉辰，比用课。古断以干上酉为日鬼主思虑，支上未为妻家、辰为脾肌肤，串成“私情失物—思虑伤脾”的象法链；现代仅作古籍象法整理。",
    "chain": [
      "课体：比用，事从亲近同类处发。",
      "事类：干上酉为日鬼，古断取色欲思虑之诫。",
      "盘态：甲子日九月，日干囚；戌亥空，太常临空古断取失物。",
      "结构：三传寅酉辰，木金土相战，古断以脾土受制言消瘦。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "routes": [
      "base",
      "duxiang",
      "zhonghuang"
    ],
    "focus": {
      "hour": "申",
      "yongShen": "酉",
      "chuan": [
        "寅",
        "酉",
        "辰"
      ],
      "bianGong": "申"
    },
    "reasoning": [
      {
        "claim": "病因思虑伤脾、肌肤消瘦",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "keg",
            "ref": "酉/甲",
            "why": "干上酉为日鬼，古断主思虑压迫"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "酉",
            "why": "酉金入传克木，病象收紧"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "辰",
            "why": "辰为脾为肌肤，古断以辰土受制言消瘦"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "囚",
            "why": "甲木九月囚，抗邪之力弱"
          }
        ],
        "ruleRef": "六亲官鬼；支辰脏腑；旺衰",
        "note": "疾病内容仅为古籍象法整理，不构成医疗建议。",
        "role": "main"
      },
      {
        "claim": "失物与私情链作旁证",
        "route": "zhonghuang",
        "evidence": [
          {
            "view": "zhonghuang",
            "kind": "shiGan",
            "ref": "壬",
            "why": "申时时干壬，中黄以此为参"
          },
          {
            "view": "zhonghuang",
            "kind": "bianGan",
            "ref": "戊",
            "why": "变干戊落申宫，为财象旁证"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌亥空，古断以太常临空言失物"
          }
        ],
        "ruleRef": "中黄时干变干；旬空",
        "note": "中黄在此案只作旁证，不主病断。",
        "role": "cross"
      }
    ],
    "topics": [
      "疾病"
    ]
  },
  {
    "id": "renzhan_jiazi_017_wang_jibing",
    "title": "王牧夫占疾病：子月甲子日丑将巳时",
    "source": "壬占汇选·卷之一",
    "chapter": "占验017 王占疾病",
    "input": {
      "mj": "丑",
      "dg": "甲",
      "dz": "子",
      "hour": "巳",
      "yearGan": "乙",
      "yearZhi": "卯",
      "monthZhi": "子"
    },
    "expect": {
      "kegs": [
        "戌/甲",
        "午/戌",
        "申/子",
        "辰/申"
      ],
      "chuans": [
        "戌",
        "午",
        "寅"
      ],
      "chuanGz": [
        "甲戌",
        "庚午",
        "丙寅"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "相",
      "monthZhi": "子",
      "method": "重审",
      "zhonghuang": {
        "shiGan": "己",
        "bianGan": "己",
        "bianGong": "巳",
        "bianLq": "妻财",
        "bianInChuan": ""
      }
    },
    "original": "占病得寅午戌炎上之局。天后在下，上生午火，戌墓盖之，火不能出；炎上为狂荡，病由高兴太过所致，无碍，久而自痊。",
    "summary": "程序复算三传戌午寅，重审课，支会寅午戌火局。古断以炎上局被戌墓盖压，取“高兴太过而火郁不出”的象；此处仅复核课传局式，不作医疗判断。",
    "chain": [
      "课体：重审，病象反覆而可渐定。",
      "事类：三传戌午寅与支会成寅午戌火局，古断谓炎上。",
      "盘态：甲子日子月，日干相；戌亥空，初传戌空，火局之墓先虚。",
      "转归：古断谓“久而自痊”，属古籍断语记录；现代不作医疗建议。"
    ],
    "compliance": "以上为古籍术数案例的程序化复原与断法链路整理，仅供传统文化与算法研习参考，不构成现实判断、医疗法律或投资建议。",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "巳",
      "yongShen": "午",
      "chuan": [
        "戌",
        "午",
        "寅"
      ],
      "bianGong": "巳"
    },
    "reasoning": [
      {
        "claim": "寅午戌炎上，病由高兴太过",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "戌",
            "why": "戌为火墓，局之收束"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "午",
            "why": "午为火旺之枢"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "寅",
            "why": "寅木生火，火局得源"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "相",
            "why": "甲子日子月相，火局虽郁而未至大害"
          }
        ],
        "ruleRef": "三合局；旺衰",
        "note": "“病由高兴太过”为古籍断语，不作现代医疗诊断。",
        "role": "main"
      },
      {
        "claim": "火被戌墓盖之，久而自痊",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "戌",
            "why": "戌墓盖火，象为郁而不出"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌空则墓盖先虚，郁久有泄机"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "亥",
            "why": "戌亥同空，凶势不坚"
          }
        ],
        "ruleRef": "墓库；旬空",
        "note": "“自痊”保留为原案记录，页面需挂研习参考。",
        "role": "support"
      }
    ],
    "topics": [
      "疾病"
    ]
  },
  {
    "id": "renzhan_jiazi_002_xu_laiyi",
    "source": "《壬占汇选》卷之一 甲子日 占验002（《玉连环》）",
    "chapter": "甲子日",
    "title": "徐次宾占来意：正月甲子日子将寅时",
    "input": {
      "mj": "子",
      "dg": "甲",
      "dz": "子",
      "hour": "寅",
      "monthZhi": "寅",
      "methodHint": "占来意"
    },
    "original": "徐次宾曰：来意因失陷官钱，勾唤入官，而得惊恐，以致患脾虚下脏之疾，见祟持刃相惊；可移病人于南方，设绯幕，至第九日，南方有属马巫医，以撒火为姓名，下赤药、艾灸，书朱符，其祟自除也。",
    "summary": "发用天魁戌为财而主脾，春土无气；中传申金为鬼，末传午火为救神。断失财惊恐、脾虚下脏、祟刃相惊，并以火象制金为解。",
    "chain": [
      "课式同前而月将占时不同，程序仍复得戌申午涉害三传",
      "古断以初传戌财主失陷官钱，戌又主脾，春土无气故脾虚",
      "中传申金为鬼，古断为持刃相惊",
      "末传午火为救神，九数应九日，火象解金鬼"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；疾病与官非内容不构成医疗、法律或投资建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "寅",
      "yongShen": "午",
      "chuan": [
        "戌",
        "申",
        "午"
      ],
      "bianGong": "寅"
    },
    "reasoning": [
      {
        "claim": "失陷官钱兼脾虚下脏",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "戌",
            "why": "戌为天魁，古断为财又主脾"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "旺",
            "why": "甲木春旺克土，土弱故脾虚"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌在旬空，财象易见失陷"
          }
        ],
        "ruleRef": "支辰脏腑；旺衰；旬空",
        "note": "疾病内容为古籍断法记录，不作医疗判断。",
        "role": "main"
      },
      {
        "claim": "祟刃相惊，九日火解",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "申",
            "why": "申金为鬼，古断主刀兵相惊"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "午",
            "why": "午火克申金，古断作救神"
          },
          {
            "view": "base",
            "kind": "zhi",
            "ref": "午",
            "why": "胜光午九数，故原案言第九日"
          }
        ],
        "ruleRef": "五行制化；支辰数目",
        "note": "驱祟/符药皆为古籍叙述，仅作文献研读。",
        "role": "timing"
      }
    ],
    "expect": {
      "kegs": [
        "子/甲",
        "戌/子",
        "戌/子",
        "申/戌"
      ],
      "chuans": [
        "戌",
        "申",
        "午"
      ],
      "chuanGz": [
        "甲戌",
        "壬申",
        "庚午"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "旺",
      "monthZhi": "寅",
      "method": "涉害",
      "zhonghuang": {
        "shiGan": "丙",
        "bianGan": "庚",
        "bianGong": "寅",
        "bianLq": "官鬼"
      }
    },
    "topics": [
      "来意",
      "疾病"
    ]
  },
  {
    "id": "renzhan_jiazi_004_shao_jibing",
    "source": "《壬占汇选》卷之一 甲子日 占验004（《张本占案》）",
    "chapter": "甲子日",
    "title": "邵彦和占疾病：六月甲子日午将申时",
    "input": {
      "mj": "午",
      "dg": "甲",
      "dz": "子",
      "hour": "申",
      "monthZhi": "未",
      "methodHint": "占疾病"
    },
    "original": "邵彦和曰：四课不足，脉息短小。发用戌土乘玄武，主脾病泻痢。中传申鬼并白虎，主沉重。然得末传午火作青龙克制虎鬼，久而自安，药宜辛温及升阳耳。",
    "summary": "四课不足而三传戌申午。戌土发用主脾病泻痢，申鬼白虎主沉重，末传午火青龙制鬼，故久而自安。",
    "chain": [
      "程序复得四课子甲/戌子/戌子/申戌，三传戌申午，天将玄白青与原案相合",
      "初传戌土乘玄武，古断主脾病泻痢",
      "中传申鬼白虎，病势沉重",
      "末传午火青龙克制虎鬼，久而自安"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；疾病内容不构成医疗建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "申",
      "yongShen": "午",
      "chuan": [
        "戌",
        "申",
        "午"
      ],
      "bianGong": "申"
    },
    "reasoning": [
      {
        "claim": "脾病泻痢而脉息短小",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "戌",
            "why": "戌土发用，古断主脾"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "戌/玄武",
            "why": "戌乘玄武，水土相混，古断为泻痢"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "囚",
            "why": "甲木六月囚，正气体弱故脉息短小"
          }
        ],
        "ruleRef": "支辰脏腑；天将；旺衰",
        "note": "疾病内容为古籍断法记录，不作医疗建议。",
        "role": "main"
      },
      {
        "claim": "沉重而久而自安",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "申",
            "why": "申金为鬼"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "申/白虎",
            "why": "鬼并白虎，病势沉重"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "午/青龙",
            "why": "末传午火青龙克制虎鬼，故久安"
          }
        ],
        "ruleRef": "五行制化；天将吉凶",
        "note": "“药宜辛温升阳”为原案记录，不作用药建议。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "子/甲",
        "戌/子",
        "戌/子",
        "申/戌"
      ],
      "chuans": [
        "戌",
        "申",
        "午"
      ],
      "chuanGz": [
        "甲戌",
        "壬申",
        "庚午"
      ],
      "chuanJiang": [
        "玄武",
        "白虎",
        "青龙"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "囚",
      "monthZhi": "未",
      "method": "涉害",
      "zhonghuang": {
        "shiGan": "壬",
        "bianGan": "戊",
        "bianGong": "申",
        "bianLq": "妻财",
        "bianInChuan": "中传"
      }
    },
    "topics": [
      "疾病"
    ]
  },
  {
    "id": "renzhan_jiazi_005_fanli_wuwang",
    "source": "《壬占汇选》卷之一 甲子日 占验005（《直指》引《吴越春秋》）",
    "chapter": "甲子日",
    "title": "范蠡占吴王病：三月甲子日酉将酉时",
    "input": {
      "mj": "酉",
      "dg": "甲",
      "dz": "子",
      "hour": "酉",
      "monthZhi": "辰",
      "methodHint": "占疾病"
    },
    "original": "范蠡曰：德禄在寅，病在巳，绝在申，春木旺金囚，无伤也。己巳日有瘳，壬申日痊愈。",
    "summary": "春木旺而金囚，甲德禄在寅，病在巳、绝在申；原案断无伤，以巳申应愈期。",
    "chain": [
      "程序复得伏吟课，三传寅巳申",
      "寅为甲德禄，春木旺，故无伤",
      "巳为病、申为绝，恰入中末传",
      "原案以己巳有瘳、壬申痊愈应期"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；疾病内容不构成医疗建议",
    "routes": [
      "base",
      "duxiang"
    ],
    "focus": {
      "hour": "酉",
      "yongShen": "寅",
      "chuan": [
        "寅",
        "巳",
        "申"
      ],
      "bianGong": "酉"
    },
    "reasoning": [
      {
        "claim": "春木旺金囚，无伤",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "囚",
            "why": "程序按月令辰判甲木囚，提示此处月令口径需校"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "寅",
            "why": "寅为甲德禄，原案以此为根"
          },
          {
            "view": "base",
            "kind": "method",
            "ref": "伏吟",
            "why": "伏吟主事情在本宫反复，病势可绵延"
          }
        ],
        "ruleRef": "德禄；月令旺衰；课体",
        "note": "原文“春木旺”与程序辰月判囚存在口径差，已标存疑，需校月令/节气。",
        "role": "main"
      },
      {
        "claim": "病在巳、绝在申，巳申应期",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "巳",
            "why": "巳为病地，入中传"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "申",
            "why": "申为绝地，入末传"
          },
          {
            "view": "base",
            "kind": "hour",
            "ref": "酉",
            "why": "酉时金旺，原案仍以春木旺论无伤，宜存疑对读"
          }
        ],
        "ruleRef": "十二运；应期取象",
        "note": "应期“己巳/壬申”为原案记录，仅作文献参照。",
        "role": "timing"
      }
    ],
    "expect": {
      "kegs": [
        "寅/甲",
        "寅/寅",
        "子/子",
        "子/子"
      ],
      "chuans": [
        "寅",
        "巳",
        "申"
      ],
      "chuanGz": [
        "丙寅",
        "己巳",
        "壬申"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "囚",
      "monthZhi": "辰",
      "method": "伏吟",
      "zhonghuang": {
        "shiGan": "癸",
        "bianGan": "辛",
        "bianGong": "酉",
        "bianLq": "官鬼"
      }
    },
    "topics": [
      "疾病"
    ]
  },
  {
    "id": "renzhan_yichou_021_chen_huishi",
    "source": "《壬占汇选》卷之一 乙丑日 占验021（《指南》）",
    "chapter": "乙丑日",
    "title": "陈公献占会试：崇正癸未年二月乙丑日亥将卯时",
    "input": {
      "mj": "亥",
      "dg": "乙",
      "dz": "丑",
      "hour": "卯",
      "yg": "癸",
      "yz": "未",
      "monthZhi": "寅",
      "methodHint": "占会试"
    },
    "original": "陈公献曰：此课占会试，必中无疑。缘传将递生，格合周遍，且干支交车生合，主文思滔滔，题目合举子之意。又喜朱雀乘旺气遁丙奇，主文章华藻，正合时宜，试官必然首荐，高登黄甲矣。果验。",
    "summary": "元首课，三传巳丑酉，传将递生而格合周遍。古断以交车生合、朱雀旺气遁丙奇主文思华藻，会试得中。",
    "chain": [
      "程序复得元首课，三传巳丑酉，天将青蛇玄",
      "传将递生、干支交车生合，古断主文思滔滔",
      "朱雀乘旺气遁丙奇，主文章华藻",
      "原案断“必中无疑”，果验"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考，不构成现实考试或决策建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "卯",
      "yongShen": "巳",
      "chuan": [
        "巳",
        "丑",
        "酉"
      ],
      "bianGong": "卯"
    },
    "reasoning": [
      {
        "claim": "会试必中无疑",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "method",
            "ref": "元首",
            "why": "元首课顺上，古断为体用得位"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "巳",
            "why": "巳火泄乙木而生土，传生之端"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "酉",
            "why": "末传酉金虽克日，原案以递生周遍论吉"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "旺",
            "why": "乙木二月旺，文气有根"
          }
        ],
        "ruleRef": "课体；传将递生；旺衰",
        "note": "科举断语仅作古籍断法研读。",
        "role": "main"
      },
      {
        "claim": "文章华藻，试官首荐",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "jiang",
            "ref": "巳/青龙",
            "why": "初传巳乘青龙，文气发扬"
          },
          {
            "view": "base",
            "kind": "zhi",
            "ref": "巳",
            "why": "巳为朱雀本位，古断主文章"
          },
          {
            "view": "zhonghuang",
            "kind": "bianGong",
            "ref": "卯",
            "why": "中黄变干丁落卯宫，仅作文气旁证"
          }
        ],
        "ruleRef": "朱雀文章；中黄旁证",
        "note": "“遁丙奇”需另校遁干表，此处不强锚。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "子/乙",
        "申/子",
        "酉/丑",
        "巳/酉"
      ],
      "chuans": [
        "巳",
        "丑",
        "酉"
      ],
      "chuanGz": [
        "辛巳",
        "丁丑",
        "乙酉"
      ],
      "chuanJiang": [
        "青龙",
        "螣蛇",
        "玄武"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "旺",
      "monthZhi": "寅",
      "method": "元首",
      "zhonghuang": {
        "shiGan": "己",
        "bianGan": "丁",
        "bianGong": "卯",
        "bianLq": "子孙"
      }
    },
    "topics": [
      "会试"
    ]
  },
  {
    "id": "renzhan_yichou_022_shao_liujia",
    "source": "《壬占汇选》卷之一 乙丑日 占验022（《方本占案》）",
    "chapter": "乙丑日",
    "title": "邵彦和占六甲：七月乙丑日午将申时",
    "input": {
      "mj": "午",
      "dg": "乙",
      "dz": "丑",
      "hour": "申",
      "monthZhi": "申",
      "methodHint": "占生产"
    },
    "original": "邵彦和曰：此课主母死子存。书云：支是母兮干是儿。今天后被支所克发传，中末又归凶将，白虎乘墓入酉之内门。内门者，产户也，故主母死。子存者，乙干是儿，乘寅为少阳，朱雀火又临其上，乙日木旺火相，日干得旺相气，故主儿存也。",
    "summary": "重审课，三传亥酉未。古断以天后被支克发传、白虎乘墓入内门主母凶；乙干乘寅得少阳、朱雀火临之，主子存。",
    "chain": [
      "程序复得重审课，三传亥酉未，天将后玄虎",
      "初传亥天后被支丑土所克，古断主母受克",
      "中末酉玄未虎，凶将相承",
      "乙干乘寅为少阳，古断以日干旺相主子存"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；生产与疾病内容不构成医疗建议",
    "routes": [
      "base",
      "duxiang"
    ],
    "focus": {
      "hour": "申",
      "yongShen": "寅",
      "chuan": [
        "亥",
        "酉",
        "未"
      ],
      "bianGong": "申"
    },
    "reasoning": [
      {
        "claim": "主母死子存",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "亥",
            "why": "亥乘天后发传，天后为母象"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "亥/天后",
            "why": "天后被支土所克，古断母受克"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "未/白虎",
            "why": "末传未乘白虎，凶将收束"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "亥",
            "why": "亥在旬空，母象更虚"
          }
        ],
        "ruleRef": "干支母子；天将；旬空",
        "note": "生死断语为古籍占案记录，现代不作医疗或现实判断。",
        "role": "main"
      },
      {
        "claim": "子存之象",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "keg",
            "ref": "寅/乙",
            "why": "乙干上乘寅，古断为少阳之气"
          },
          {
            "view": "base",
            "kind": "zhi",
            "ref": "寅",
            "why": "寅木扶乙，日干有根"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "死",
            "why": "程序按申月判乙木死，提示原文“木旺”口径需校"
          }
        ],
        "ruleRef": "日干旺衰；支辰生扶",
        "note": "原文“乙日木旺火相”与程序申月判死不一致，按存疑对读。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "寅/乙",
        "子/寅",
        "亥/丑",
        "酉/亥"
      ],
      "chuans": [
        "亥",
        "酉",
        "未"
      ],
      "chuanGz": [
        "丁亥",
        "乙酉",
        "癸未"
      ],
      "chuanJiang": [
        "天后",
        "玄武",
        "白虎"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "死",
      "monthZhi": "申",
      "method": "重审",
      "zhonghuang": {
        "shiGan": "甲",
        "bianGan": "壬",
        "bianGong": "申",
        "bianLq": "父母"
      }
    },
    "topics": [
      "生产"
    ]
  },
  {
    "id": "renzhan_yichou_024_xu_laiyi",
    "source": "《壬占汇选》卷之一 乙丑日 占验024（《一字诀玉连环》）",
    "chapter": "乙丑日",
    "title": "徐次宾占来意：六月乙丑日午将未时",
    "input": {
      "mj": "午",
      "dg": "乙",
      "dz": "丑",
      "hour": "未",
      "monthZhi": "未",
      "methodHint": "占来意"
    },
    "original": "徐次宾曰：来意事干西北方，承继姓王人财产，相托一属鼠有官人，九月内定见成就。又目下西南方，虚望外财，道路有所畏隔，不敢往也。",
    "summary": "重审课，三传子亥戌。古断以末传戌财临亥应西北王姓财产，初传子贵人为属鼠有官人，九月戌建主成就；未时财逢天空、白虎主道路畏隔。",
    "chain": [
      "程序复得重审课，三传子亥戌，天将贵后阴",
      "末传戌为日干之财，戌亥西北，古断应王姓财产",
      "初传子乘贵人，子属鼠，故有官人相托",
      "未时阴神天空、事门白虎，主虚望与道路畏隔"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考，不构成财产、法律或投资决策建议",
    "routes": [
      "base",
      "duxiang",
      "yongshen"
    ],
    "focus": {
      "hour": "未",
      "yongShen": "戌",
      "chuan": [
        "子",
        "亥",
        "戌"
      ],
      "bianGong": "未"
    },
    "reasoning": [
      {
        "claim": "西北方承继王姓财产，属鼠官人相托",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "戌",
            "why": "戌为天魁，乙日以土为财"
          },
          {
            "view": "base",
            "kind": "zhi",
            "ref": "亥",
            "why": "戌临亥宫，西北之象"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "子",
            "why": "子属鼠，为三合水局之端"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "子/贵人",
            "why": "子乘天乙贵人，古断为有官人"
          }
        ],
        "ruleRef": "支辰方位；贵人；财爻",
        "note": "财产承继内容仅作古籍断法研读，不构成法律建议。",
        "role": "main"
      },
      {
        "claim": "西南虚望外财，道路畏隔",
        "route": "yongshen",
        "evidence": [
          {
            "view": "base",
            "kind": "hour",
            "ref": "未",
            "why": "未为乙日财方，原案以时取目下之事"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌空，外财终成虚望"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "戌",
            "why": "末传戌财落空，成就需待填实"
          }
        ],
        "ruleRef": "时财；旬空；事门",
        "note": "“天空/白虎”锚点需补神将宫位列后再强校验。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "卯/乙",
        "寅/卯",
        "子/丑",
        "亥/子"
      ],
      "chuans": [
        "子",
        "亥",
        "戌"
      ],
      "chuanGz": [
        "丙子",
        "丁亥",
        "丙戌"
      ],
      "chuanJiang": [
        "贵人",
        "天后",
        "太阴"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "囚",
      "monthZhi": "未",
      "method": "重审",
      "zhonghuang": {
        "shiGan": "癸",
        "bianGan": "己",
        "bianGong": "未",
        "bianLq": "妻财"
      }
    },
    "topics": [
      "来意"
    ]
  },
  {
    "id": "renzhan_yichou_028_chen_shihuan",
    "source": "《壬占汇选》卷之一 乙丑日 占验028（《指南》）",
    "chapter": "乙丑日",
    "title": "陈公献占仕宦：顺治甲申年二月乙丑日亥将申时",
    "input": {
      "mj": "亥",
      "dg": "乙",
      "dz": "丑",
      "hour": "申",
      "yg": "甲",
      "yz": "申",
      "monthZhi": "寅",
      "methodHint": "占进京补官"
    },
    "original": "陈公献曰：必不能北行，即行亦必半途而旋。盖因干支乘墓，所为不通，况课传年命未见二马，干神归支，利静而不利动，又中末二传空亡，主半道言旋。但青龙居干发用，今年却要起官，必补尚宝之职，因年上酉乃印也。阴神见贵人生日，岂非司印乎？后闻李贼陷京，因未北上，而官南京尚宝。",
    "summary": "重审课，三传未戌丑。古断以干支乘墓、课传年命无马、中末空亡主不能北行；又以年上酉印、贵人生日断补尚宝。",
    "chain": [
      "程序复得重审课，三传未戌丑",
      "古断以干支乘墓、无马、空亡主北行不遂",
      "中末戌丑临空，主半途而旋",
      "年上酉为印，阴神贵人生日，原案断补尚宝"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考，不构成现实仕途或决策建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "申",
      "yongShen": "未",
      "chuan": [
        "未",
        "戌",
        "丑"
      ],
      "bianGong": "申"
    },
    "reasoning": [
      {
        "claim": "必不能北行，即行亦半途而旋",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "method",
            "ref": "重审",
            "why": "重审课事多阻滞"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "戌",
            "why": "中传戌空，动象不实"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌亥旬空，中末空亡故主半道言旋"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "旺",
            "why": "乙木二月旺，利守成不利妄动"
          }
        ],
        "ruleRef": "课体；旬空；旺衰",
        "note": "原案“青龙居干发用”与程序天将序列不完全同式，入库不强锚。",
        "role": "main"
      },
      {
        "claim": "今年起官，补尚宝之职",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "zhi",
            "ref": "酉",
            "why": "原案以年上酉为印"
          },
          {
            "view": "base",
            "kind": "hour",
            "ref": "申",
            "why": "申时金旺，官象有气"
          },
          {
            "view": "zhonghuang",
            "kind": "bianGong",
            "ref": "申",
            "why": "中黄变干壬落申宫，仅作官印旁证"
          }
        ],
        "ruleRef": "年上神；贵人；中黄旁证",
        "note": "尚宝司断语保留为原案记录。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "未/乙",
        "戌/未",
        "辰/丑",
        "未/辰"
      ],
      "chuans": [
        "未",
        "戌",
        "丑"
      ],
      "chuanGz": [
        "癸未",
        "丙戌",
        "丁丑"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "旺",
      "monthZhi": "寅",
      "method": "重审",
      "zhonghuang": {
        "shiGan": "甲",
        "bianGan": "壬",
        "bianGong": "申",
        "bianLq": "父母"
      }
    },
    "topics": [
      "仕宦",
      "补官"
    ]
  },
  {
    "id": "renzhan_yichou_030_shao_yishi",
    "source": "《壬占汇选》卷之一 乙丑日 占验030（《方本占案》《口鉴》）",
    "chapter": "乙丑日",
    "title": "邵彦和占役事：建炎己酉年九月乙丑日卯将戌时",
    "input": {
      "mj": "卯",
      "dg": "乙",
      "dz": "丑",
      "hour": "戌",
      "yg": "己",
      "yz": "酉",
      "monthZhi": "戌",
      "methodHint": "占脱役事"
    },
    "original": "邵彦和曰：保正不能脱手，于道理上合当做此役也。酉加乙作蛇，官鬼自缠其身，初传功曹，身已在公了；若不认此役，须被监系，必待认了方释。末传子未相穿，又作勾陈，断然难脱，脱后又重做也。",
    "summary": "涉害课，三传寅未子。古断以酉鬼加乙、螣蛇缠身，初传寅天空为吏役，中传未天后主认了无虑，末传子勾陈穿未，主难脱且脱后重做。",
    "chain": [
      "程序复得涉害课，三传寅未子，天将空后勾与原案相合",
      "酉加乙作蛇，官鬼自缠",
      "初传寅天空，古断为吏役",
      "末传子勾陈穿未，主难脱"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；役事官非内容不构成法律建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "戌",
      "yongShen": "寅",
      "chuan": [
        "寅",
        "未",
        "子"
      ],
      "bianGong": "戌"
    },
    "reasoning": [
      {
        "claim": "保正不能脱手",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "keg",
            "ref": "酉/乙",
            "why": "酉金克乙，官鬼临干"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "寅/天空",
            "why": "初传寅乘天空，古断为吏役"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "子",
            "why": "末传子与未穿，事端缠结"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "子/勾陈",
            "why": "子乘勾陈，主羁缠难脱"
          }
        ],
        "ruleRef": "六亲官鬼；天将；六害",
        "note": "“监系/入狱”为古籍断语，不作现实法律判断。",
        "role": "main"
      },
      {
        "claim": "认了方释，脱后重做",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "jiang",
            "ref": "未/天后",
            "why": "中传未乘天后，古断为和解之口"
          },
          {
            "view": "base",
            "kind": "method",
            "ref": "涉害",
            "why": "涉害课主受害受累，事不即解"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "囚",
            "why": "乙木九月囚，身力受制"
          }
        ],
        "ruleRef": "课体；旺衰",
        "note": "原案“九年又做一次”为占验记录，仅作文献参照。",
        "role": "risk"
      }
    ],
    "expect": {
      "kegs": [
        "酉/乙",
        "寅/酉",
        "午/丑",
        "亥/午"
      ],
      "chuans": [
        "寅",
        "未",
        "子"
      ],
      "chuanJiang": [
        "天空",
        "天后",
        "勾陈"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "囚",
      "monthZhi": "戌",
      "method": "涉害",
      "zhonghuang": {
        "shiGan": "丙",
        "bianGan": "戊",
        "bianGong": "戌",
        "bianLq": "妻财",
        "bianInChuan": "末传"
      }
    },
    "topics": [
      "役事"
    ]
  },
  {
    "id": "renzhan_yichou_031_wang_furen",
    "source": "《壬占汇选》卷之一 乙丑日 占验031（《牧夫占验》）",
    "chapter": "乙丑日",
    "title": "王牧夫占复任：乾隆己巳年五月乙丑日未将丑时",
    "input": {
      "mj": "未",
      "dg": "乙",
      "dz": "丑",
      "hour": "丑",
      "yg": "己",
      "yz": "巳",
      "monthZhi": "午",
      "methodHint": "占盐院复任"
    },
    "original": "王牧夫曰：今戌辰戌，辰为新，戌为旧，今戌居始末，是旧官复莅任也。夏占火墓发用，虽空，然得时之旺气，况反复仍归干上，干为外，故仍莅外任也。将来戌旺辰衰，则旧官至矣。来期其在夏秋之交乎？果于六月末旬，立秋前一日到。",
    "summary": "返吟课，三传戌辰戌。古断以戌居始末为旧官复莅，返吟反复仍归干上主外任；戌虽空而得时，旧官于夏秋之交至。",
    "chain": [
      "程序复得返吟课，三传戌辰戌，天将朱常朱",
      "戌居始末，古断为旧官复莅",
      "返吟反复归干，干为外任",
      "戌空而逢火月，原案以得时论旧官至"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考，不构成现实仕途或决策建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "丑",
      "yongShen": "戌",
      "chuan": [
        "戌",
        "辰",
        "戌"
      ],
      "bianGong": "丑"
    },
    "reasoning": [
      {
        "claim": "旧官复莅任",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "戌",
            "why": "戌居始，古断为旧"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "辰",
            "why": "辰居其中，古断为新"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "戌",
            "why": "末传复归戌，旧事回头"
          },
          {
            "view": "base",
            "kind": "method",
            "ref": "返吟",
            "why": "返吟主反复，故旧官复至"
          }
        ],
        "ruleRef": "新旧取象；返吟",
        "note": "新旧官吏断法为古籍象法整理。",
        "role": "main"
      },
      {
        "claim": "仍莅外任，夏秋之交至",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌空，来期需待填实"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "戌/朱雀",
            "why": "戌乘朱雀，文书信息之象"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "休",
            "why": "乙木五月休，宜守待时"
          }
        ],
        "ruleRef": "旬空；天将；旺衰",
        "note": "应期“立秋前一日到”为原案记录，仅作文献参照。",
        "role": "timing"
      }
    ],
    "expect": {
      "kegs": [
        "戌/乙",
        "辰/戌",
        "未/丑",
        "丑/未"
      ],
      "chuans": [
        "戌",
        "辰",
        "戌"
      ],
      "chuanJiang": [
        "朱雀",
        "太常",
        "朱雀"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "休",
      "monthZhi": "午",
      "method": "返吟",
      "zhonghuang": {
        "shiGan": "丁",
        "bianGan": "辛",
        "bianGong": "丑",
        "bianLq": "官鬼"
      }
    },
    "topics": [
      "仕宦",
      "复任"
    ]
  },
  {
    "id": "renzhan_bingyin_035_miao_guansong",
    "source": "《壬占汇选》卷之一 丙寅日 占验035（《一针见血》《玉连环》末卷）",
    "chapter": "丙寅日",
    "title": "苗公达占官讼：天圣六年戊辰五月丙寅日申将丑时",
    "input": {
      "mj": "申",
      "dg": "丙",
      "dz": "寅",
      "hour": "丑",
      "yg": "戊",
      "yz": "辰",
      "monthZhi": "午",
      "methodHint": "占讼"
    },
    "original": "苗公达曰：主门户不宁。卑幼为尊长所欺，反有词讼，须坐狱两旬，必有贵人释罪。来日丁卯，便见官入狱也。果是兄讼其弟，得大尹劝和。",
    "summary": "比用课，三传子未寅。古断以魁罡蛇虎立卯酉主门户不宁，三上克下主尊凌卑；传中合阴龙吉神，又得贵人临支，故终归和允释罪。",
    "chain": [
      "程序复得比用课，三传子未寅，天将合阴青",
      "原案以门户不宁、尊凌卑断词讼起因",
      "戌亥旬空而戌为日墓，古断坐狱两旬",
      "传中六合太阴青龙皆吉，主和允释罪"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；官讼内容不构成法律建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "丑",
      "yongShen": "子",
      "chuan": [
        "子",
        "未",
        "寅"
      ],
      "bianGong": "丑"
    },
    "reasoning": [
      {
        "claim": "门户不宁，尊长欺卑幼",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "method",
            "ref": "比用",
            "why": "比用课主亲近相争"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "子",
            "why": "神后子水发用克丙，争端起自外制"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌为日墓而空，狱象有期"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "旺",
            "why": "丙火五月旺，不畏上神而反成争讼"
          }
        ],
        "ruleRef": "课体；旺衰；旬空",
        "note": "官讼断语为古籍记录，不作现实法律判断。",
        "role": "main"
      },
      {
        "claim": "两旬后贵人释罪，终得和允",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "jiang",
            "ref": "子/六合",
            "why": "初传子乘六合，有和解之机"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "未/太阴",
            "why": "中传未乘太阴，主暗中调护"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "寅/青龙",
            "why": "末传寅乘青龙，吉神收束"
          }
        ],
        "ruleRef": "天将吉凶；旬首应期",
        "note": "“丁卯日见官入狱”为原案应期记录，仅作文献参照。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "子/丙",
        "未/子",
        "酉/寅",
        "辰/酉"
      ],
      "chuans": [
        "子",
        "未",
        "寅"
      ],
      "chuanJiang": [
        "六合",
        "太阴",
        "青龙"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "旺",
      "monthZhi": "午",
      "method": "比用",
      "zhonghuang": {
        "shiGan": "己",
        "bianGan": "乙",
        "bianGong": "丑",
        "bianLq": "父母"
      }
    },
    "topics": [
      "官讼"
    ]
  },
  {
    "id": "renzhan_bingyin_038_liu_xingren",
    "source": "《壬占汇选》卷之一 丙寅日 占验038（《玉连环》末卷）",
    "chapter": "丙寅日",
    "title": "刘日新占行人：九月丙寅日卯将卯时",
    "input": {
      "mj": "卯",
      "dg": "丙",
      "dz": "寅",
      "hour": "卯",
      "monthZhi": "戌",
      "methodHint": "占行人"
    },
    "original": "刘日新曰：此乃贵人占从人到否，须责天空。其人已动在路，已乃地足为用，更在日辰上，主亥日当到。末寅作六合，乃船车动也。又寅申巳亥，乃传终也。",
    "summary": "伏吟课，三传巳申寅。古断以天空为用、巳临日辰主行人已动在路；末传寅六合主船车动，亥日当到。",
    "chain": [
      "程序复得伏吟课，三传巳申寅，天将空玄合",
      "巳为地足为用又临日辰，主已动在路",
      "末传寅乘六合，古断为船车动",
      "寅申巳亥为传终，主归期可定"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考，不构成现实出行判断或建议",
    "routes": [
      "base",
      "duxiang",
      "yongshen"
    ],
    "focus": {
      "hour": "卯",
      "yongShen": "巳",
      "chuan": [
        "巳",
        "申",
        "寅"
      ],
      "bianGong": "卯"
    },
    "reasoning": [
      {
        "claim": "其人已动在路",
        "route": "yongshen",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "巳",
            "why": "巳为地足发用"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "巳/天空",
            "why": "巳乘天空，原案占从人到否须责天空"
          },
          {
            "view": "base",
            "kind": "keg",
            "ref": "巳/丙",
            "why": "巳临日干之上，象贴日主"
          },
          {
            "view": "base",
            "kind": "method",
            "ref": "伏吟",
            "why": "伏吟主近处动而迟发"
          }
        ],
        "ruleRef": "行人取用；伏吟",
        "note": "OCR“已乃地足”按“巳乃地足”读。",
        "role": "main"
      },
      {
        "claim": "亥日当到，船车动而归",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "寅",
            "why": "末传寅为传终"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "寅/六合",
            "why": "寅乘六合，古断为船车动"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "申",
            "why": "中传申与寅相冲，动象已成"
          }
        ],
        "ruleRef": "传终；六合车船",
        "note": "应期“亥日”为原案记录，仅作文献参照。",
        "role": "timing"
      }
    ],
    "expect": {
      "kegs": [
        "巳/丙",
        "巳/巳",
        "寅/寅",
        "寅/寅"
      ],
      "chuans": [
        "巳",
        "申",
        "寅"
      ],
      "chuanJiang": [
        "天空",
        "玄武",
        "六合"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "囚",
      "monthZhi": "戌",
      "method": "伏吟",
      "zhonghuang": {
        "shiGan": "辛",
        "bianGan": "辛",
        "bianGong": "卯",
        "bianLq": "妻财"
      }
    },
    "topics": [
      "行人"
    ]
  },
  {
    "id": "renzhan_bingyin_039_shao_furen",
    "source": "《壬占汇选》卷之一 丙寅日 占验039（《口鉴》）",
    "chapter": "丙寅日",
    "title": "邵彦和占赴任：建炎戊申年六月丙寅日未将巳时",
    "input": {
      "mj": "未",
      "dg": "丙",
      "dz": "寅",
      "hour": "巳",
      "yg": "戊",
      "yz": "申",
      "monthZhi": "未",
      "methodHint": "占赴任"
    },
    "original": "邵彦和曰：辰午申登三天课，因高峻而致危险。占行人不归，占疾病不起，今经幹占赴任得此，万不可往，恐有去无回。来年行年到寅，正是登三天，尤不可往也。经幹不信，于己酉年七月动身赴任，八月到京西，庚戌年五月病死。",
    "summary": "重审课而三传辰午申，古称登三天。邵彦和以此课高峻危险，赴任不宜往；原案记录其后赴任病死、家眷不得归。",
    "chain": [
      "程序复得三传辰午申，确为登三天序",
      "古断以登高致险，赴任忌往",
      "原案又以来年行年到寅加重其断",
      "占验结果只作文献记录，不作现实推演"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；疾病生死内容不构成医疗或现实判断建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "巳",
      "yongShen": "辰",
      "chuan": [
        "辰",
        "午",
        "申"
      ],
      "bianGong": "巳"
    },
    "reasoning": [
      {
        "claim": "辰午申登三天，赴任危险",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "辰",
            "why": "初传辰为登三天之始"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "午",
            "why": "中传午，地势渐高"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "申",
            "why": "末传申，登高至极"
          },
          {
            "view": "base",
            "kind": "method",
            "ref": "重审",
            "why": "重审课事多审滞，不宜轻动"
          }
        ],
        "ruleRef": "登三天课；课体",
        "note": "此课吉凶断语仅作古籍课体研读。",
        "role": "main"
      },
      {
        "claim": "有去无回之戒",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "休",
            "why": "丙火六月休，行动力不足"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "午/白虎",
            "why": "中传午乘白虎，古断以飞廉白虎致凶"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌亥旬空，归着多虚"
          }
        ],
        "ruleRef": "天将；旺衰；旬空",
        "note": "疾病死亡为原案记录，不作医疗判断。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "未/丙",
        "酉/未",
        "辰/寅",
        "午/辰"
      ],
      "chuans": [
        "辰",
        "午",
        "申"
      ],
      "chuanGz": [
        "壬辰",
        "甲午",
        "丙申"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "休",
      "monthZhi": "未",
      "method": "重审",
      "zhonghuang": {
        "shiGan": "癸",
        "bianGan": "丁",
        "bianGong": "巳",
        "bianLq": "比肩"
      }
    },
    "topics": [
      "仕宦",
      "赴任"
    ]
  },
  {
    "id": "renzhan_bingyin_044_xu_laiyi",
    "source": "《壬占汇选》卷之一 丙寅日 占验044（《一字块玉连环》）",
    "chapter": "丙寅日",
    "title": "徐次宾占来意：六月丙寅日午将未时",
    "input": {
      "mj": "午",
      "dg": "丙",
      "dz": "寅",
      "hour": "未",
      "monthZhi": "未",
      "methodHint": "占来意"
    },
    "original": "徐次宾曰：来意主北面近水酒筵间，与额尖眼小之人相争。又一贵人与彼相助照，乃息怒而欲见官，却得一姓王人劝合无事也。",
    "summary": "比用课，三传子亥戌。古断以值事太常主酒食，子亥为北面近水，神后登明为日鬼主争；日上辰土制水主息怒，末传戌临亥主王姓劝合。",
    "chain": [
      "程序复得比用课，三传子亥戌，天将蛇贵后",
      "太常临事门主酒食筵宴",
      "子亥水神为日鬼，主北面近水相争",
      "末传戌临亥，古断为王姓劝合"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；争讼内容不构成法律建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "未",
      "yongShen": "戌",
      "chuan": [
        "子",
        "亥",
        "戌"
      ],
      "bianGong": "未"
    },
    "reasoning": [
      {
        "claim": "北面近水酒筵间相争",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "子",
            "why": "神后子水发用，北面近水"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "子/螣蛇",
            "why": "子乘螣蛇，古断为额尖眼小之人"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "亥",
            "why": "中传登明亥水，亦为日鬼"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "亥/贵人",
            "why": "亥乘贵人，主有人相助照"
          }
        ],
        "ruleRef": "支辰方位；天将形貌",
        "note": "形貌断法为古籍象法，不作现实评价。",
        "role": "main"
      },
      {
        "claim": "息怒欲见官，王姓劝合无事",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "keg",
            "ref": "辰/丙",
            "why": "日上辰土制亥子水，古断主息怒"
          },
          {
            "view": "base",
            "kind": "method",
            "ref": "比用",
            "why": "比用主和合"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "戌",
            "why": "末传天魁戌临亥，原案以“王”字断姓王人劝合"
          }
        ],
        "ruleRef": "课体；支克制化；字形取象",
        "note": "见官/劝合内容仅作古籍断法研读。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "辰/丙",
        "卯/辰",
        "丑/寅",
        "子/丑"
      ],
      "chuans": [
        "子",
        "亥",
        "戌"
      ],
      "chuanJiang": [
        "螣蛇",
        "贵人",
        "天后"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "休",
      "monthZhi": "未",
      "method": "比用",
      "zhonghuang": {
        "shiGan": "乙",
        "bianGan": "癸",
        "bianGong": "未",
        "bianLq": "官鬼"
      }
    },
    "topics": [
      "来意"
    ]
  },
  {
    "id": "renzhan_bingyin_041_shao_pingsheng",
    "source": "《壬占汇选》卷之一 丙寅日 占验041（《口鉴》）",
    "chapter": "丙寅日",
    "title": "邵彦和占平生：建炎戊申年二月丙寅日亥将申时",
    "input": {
      "mj": "亥",
      "dg": "丙",
      "dz": "寅",
      "hour": "申",
      "yearGan": "戊",
      "yearZhi": "申",
      "monthZhi": "卯",
      "methodHint": "占前程"
    },
    "original": "徐教授丙子命，十一月二十一日丑时生，三十三岁，占前程。建炎戊申年二月丙寅日亥将申时。邵彦和曰：申本时临日，为日所克。丙为夫，申为妻，既从日上发用，空亡又临妻宫，必主克妻。亥数四，主克四妻。中年子息亦克，以六合不得地也。申为西南之金，到巳之炉冶上，必有声名于西北也。申为今日之马，干又坐本命之马而得长生，主为官至老不倦也。宅上丙火受寅而生，不可以外内言也。年将四旬必遇曹姓人而显官，亦终于六曹。亥为月将，不论空亡，但时少迟耳。月将乘贵人入传，四年之后，便显自绛帐，从此达于天庭。又寅来生身，十一月天马在寅，寅临天门，元武归本家，为黑煞，黑煞为刑职。中传既有天门，寅又在天门上，以天见天，必出疆见诸侯，然后人侍天子，处六曹中而带刑职也。寅申已亥为四维，主代天子而守四方，必四任也。",
    "summary": "涉害课，三传申亥寅。古断以初传申为日马兼妻财，主前程已动而家室先有伤；中传亥为月将乘贵人入传，主四年后自绛帐而显；末传寅长生临天门，主出疆入侍、终带刑职。",
    "chain": [
      "程序复得涉害课，三传申亥寅，旬空戌亥",
      "初传申为日马且自日上发用，古断主前程已动",
      "中传亥为月将乘贵人入传，古断主四年后显达",
      "末传寅为长生临天门，古断主出疆入侍、四任四方"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；官禄、刑职、婚丧内容不构成现实判断、法律或人生决策建议",
    "routes": [
      "base",
      "duxiang",
      "zhonghuang",
      "bifa"
    ],
    "focus": {
      "hour": "申",
      "yongShen": "申",
      "chuan": [
        "申",
        "亥",
        "寅"
      ],
      "bianGong": "申"
    },
    "reasoning": [
      {
        "claim": "前程已动，迟而有显",
        "route": "base",
        "evidence": [
          {
            "view": "base",
            "kind": "method",
            "ref": "涉害",
            "why": "涉害主事有艰阻而后成"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "申",
            "why": "初传申自日上发用，古断为今日之马，主前程已动",
            "mark": "马",
            "key": true
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "亥",
            "why": "中传亥为月将，古断谓月将入传，迟而非绝",
            "mark": "贵",
            "key": true
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "寅",
            "why": "末传寅为长生，古断主生身、归着有地"
          }
        ],
        "ruleRef": "九宗门；三传起承转合；月将入传",
        "note": "前程断法仅作古籍研习。",
        "role": "main"
      },
      {
        "claim": "四年后自绛帐而显",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "jiang",
            "ref": "亥/贵人",
            "why": "亥乘贵人，古断为月将乘贵人入传"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "亥",
            "why": "亥虽旬空，古断谓月将不论空亡，但时少迟"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "寅",
            "why": "末传寅临天门，古断主出疆见诸侯、入侍天子"
          }
        ],
        "ruleRef": "贵人；月将；天门",
        "note": "年数为古案应期记录，不作现实期限。",
        "role": "timing"
      },
      {
        "claim": "家室先有伤，刑职随身",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "keg",
            "ref": "申/丙",
            "why": "干上申为财，古断以财为妻象"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "亥",
            "why": "传本有空亡临妻宫之说，程序旬空在戌亥，宜并看存疑"
          },
          {
            "view": "base",
            "kind": "gong",
            "ref": "寅",
            "why": "古断以寅临天门、黑煞归家，主带刑职"
          }
        ],
        "ruleRef": "妻财；空亡；黑煞",
        "note": "刑丧内容只还原古断链条，不作现实断语。",
        "role": "risk"
      }
    ],
    "expect": {
      "kegs": [
        "申/丙",
        "亥/申",
        "巳/寅",
        "申/巳"
      ],
      "chuans": [
        "申",
        "亥",
        "寅"
      ],
      "chuanGz": [
        "丙申",
        "己亥",
        "庚寅"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "休",
      "monthZhi": "卯",
      "method": "涉害",
      "zhonghuang": {
        "shiGan": "丙",
        "bianGan": "丙",
        "bianGong": "申",
        "bianLq": "比肩",
        "bianInChuan": "初传"
      }
    },
    "topics": [
      "前程",
      "终身"
    ]
  },
  {
    "id": "renzhan_bingyin_042_shao_shenwei",
    "source": "《壬占汇选》卷之一 丙寅日 占验042（《口鉴》、方本作《占案》）",
    "chapter": "丙寅日",
    "title": "邵彦和占身位：戊申年六月丙寅日未将寅时",
    "input": {
      "mj": "未",
      "dg": "丙",
      "dz": "寅",
      "hour": "寅",
      "yearGan": "戊",
      "yearZhi": "申",
      "monthZhi": "未",
      "methodHint": "占身位"
    },
    "original": "何三公，丙午生，六十三岁，占身位。戊申年六月丙寅日未将寅时。邵彦和曰：干支带墓，第四课见子鬼发动，却又传归日上；六月死神在戌，作蛇，主有伏尸，带迷惑煞，殃及于人。因宅中皆是旧墓，前后俱有尸骸，鬼入四课，在内之鬼也。传出日上，渐次侵害于人也。主不出八年，痨病相缠，当死五人。中传虽有生气，受克化而为鬼，是以不利。戌年戌月，难以救也。考何三公宅内，原是旧冢，闻此言，乃掘之，共掘出十四穴，皆无主之墓。庚戌年九月未日，何公不禄。七年之内，果丧五人。",
    "summary": "比用课，三传子巳戌。古断以第四课子鬼发动、传归日上，主内鬼渐侵；末传戌为死神作螣蛇，主旧墓伏尸；中传巳虽生气而受克化鬼，故应七年丧五人。",
    "chain": [
      "程序复得比用课，三传子巳戌，天将合常蛇",
      "第四课子水为官鬼发动，古断主内鬼入传",
      "末传戌为六月死神作螣蛇，古断主旧墓伏尸",
      "中传巳为生气而受克化鬼，古断主难救"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；疾病、死亡、宅墓内容不构成现实判断、医疗或法律建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "寅",
      "yongShen": "戌",
      "chuan": [
        "子",
        "巳",
        "戌"
      ],
      "bianGong": "寅"
    },
    "reasoning": [
      {
        "claim": "身位主旧墓伏尸，内鬼渐侵",
        "route": "base",
        "evidence": [
          {
            "view": "base",
            "kind": "keg",
            "ref": "子/未",
            "why": "第四课见子，子为日鬼，古断谓鬼入四课"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "初传",
            "ref": "子",
            "why": "初传子鬼发动，古断主在内之鬼渐侵于人",
            "mark": "鬼",
            "key": true
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "戌",
            "why": "末传戌传归日上，古断以六月死神在戌，主伏尸",
            "mark": "尸",
            "key": true
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "戌/螣蛇",
            "why": "戌乘螣蛇，古断为死神作蛇、带迷惑煞"
          }
        ],
        "ruleRef": "官鬼；死神；天将",
        "note": "宅墓死亡内容仅作古案复原。",
        "role": "main"
      },
      {
        "claim": "不出八年，戌年戌月难救",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "method",
            "ref": "比用",
            "why": "比用主事情相染相缠"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "戌",
            "why": "末传戌为归着，古断应戌年戌月"
          },
          {
            "view": "base",
            "kind": "dayWangShuai",
            "ref": "休",
            "why": "日干休囚，古断谓难以救解"
          }
        ],
        "ruleRef": "课体；末传归着；旺衰",
        "note": "应期为古案记录，不作现实期限。",
        "role": "timing"
      },
      {
        "claim": "中传生气受克，反化为鬼",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "巳",
            "why": "中传巳为生气，古断谓受克化而为鬼"
          },
          {
            "view": "base",
            "kind": "jiang",
            "ref": "巳/太常",
            "why": "巳乘太常，古断仍不以吉论，重在受克"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌亥旬空，末传戌空，凶象有名实之辨"
          }
        ],
        "ruleRef": "生克；空亡；三传化气",
        "note": "此处传本象法较细，宜作参证。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "戌/丙",
        "卯/戌",
        "未/寅",
        "子/未"
      ],
      "chuans": [
        "子",
        "巳",
        "戌"
      ],
      "chuanGz": [
        "戊子",
        "癸巳",
        "戊戌"
      ],
      "chuanJiang": [
        "六合",
        "太常",
        "螣蛇"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "休",
      "monthZhi": "未",
      "method": "比用",
      "zhonghuang": {
        "shiGan": "庚",
        "bianGan": "戊",
        "bianGong": "寅",
        "bianLq": "子孙",
        "bianInChuan": ""
      }
    },
    "topics": [
      "己身",
      "风水",
      "疾病"
    ]
  },
  {
    "id": "renzhan_bingyin_045_huang_zhongshen",
    "source": "《壬占汇选》卷之一 丙寅日 占验045（《残篇》）",
    "chapter": "丙寅日",
    "title": "黄氏占终身：康熙乙丑岁五月丙寅日申将酉时",
    "input": {
      "mj": "申",
      "dg": "丙",
      "dz": "寅",
      "hour": "酉",
      "yearGan": "乙",
      "yearZhi": "丑",
      "monthZhi": "巳",
      "methodHint": "占终身"
    },
    "original": "吴公望问终身，即以生年月日时演课断之。康熙二十四年，乙丑岁五月初七丙寅日申将酉时。黄断曰：初传旬仪，二十岁以前，自在快活之场，有无边之乐事。干支上神虽系龙常，各载鬼墓，鬼亦官也，官星入墓，功名有不蹭蹬者乎？宜其十赴棘闱而悲于不遇耳。况甲科最要帘幕贵人得力，中传亥，幕贵也，兼是官星，乃又旬空，空则无力也。欲填实，除是有亥年之恩科，则填补而可望。又或有巳年之恩科，冲实亦可望，否则不能矣。末传子息又空，乃是天将后加，后，妻也，妻室空而尚能育子乎？故须觅一肖夫之妾以填补之。邓攸之哭，吾知其可免矣。",
    "summary": "比用课，三传子亥戌。古断以干支上神虽吉而各载鬼墓，主功名蹭蹬；中传亥为幕贵兼官星而旬空，主甲科无力；末传戌空，古断又及妻室子息之虑。残篇末段 OCR 有缺，仅据存文整理。",
    "chain": [
      "程序复得比用课，三传子亥戌，旬空戌亥",
      "干支上神虽系吉将，古断谓各载鬼墓，主功名蹭蹬",
      "中传亥为幕贵兼官星而旬空，主科名无力",
      "末传戌空，古断又及妻室子息，但残篇末段有缺文"
    ],
    "compliance": "古籍案例整理，仅供传统文化研习参考；功名、婚育、子息内容不构成现实判断或人生决策建议",
    "routes": [
      "base",
      "duxiang",
      "bifa"
    ],
    "focus": {
      "hour": "酉",
      "yongShen": "亥",
      "chuan": [
        "子",
        "亥",
        "戌"
      ],
      "bianGong": "酉"
    },
    "reasoning": [
      {
        "claim": "终身功名蹭蹬，幕贵空而无力",
        "route": "base",
        "evidence": [
          {
            "view": "base",
            "kind": "keg",
            "ref": "辰/丙",
            "why": "干上辰，古断谓干支上神各载鬼墓"
          },
          {
            "view": "base",
            "kind": "keg",
            "ref": "丑/寅",
            "why": "支上丑，与干上辰并见，古断主官星入墓"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "亥",
            "why": "中传亥为幕贵兼官星，古断谓甲科最要此处得力",
            "mark": "幕",
            "key": true
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "亥",
            "why": "亥又旬空，古断谓空则无力",
            "mark": "空",
            "key": true
          }
        ],
        "ruleRef": "干支上神；幕贵；空亡",
        "note": "科名断法仅作古籍研习。",
        "role": "main"
      },
      {
        "claim": "亥年填实、巳年冲实，方可望科名",
        "route": "duxiang",
        "evidence": [
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "亥",
            "why": "亥空待填，古断以亥年恩科为填实"
          },
          {
            "view": "base",
            "kind": "chuan",
            "pos": "中传",
            "ref": "亥",
            "why": "中传亥为本案科名关键"
          },
          {
            "view": "base",
            "kind": "zhi",
            "ref": "巳",
            "why": "古断谓巳年冲实亦可望"
          }
        ],
        "ruleRef": "空亡填实；冲实",
        "note": "应期为古案条件句，不作现实期限。",
        "role": "timing"
      },
      {
        "claim": "末传空，兼及妻室子息",
        "route": "bifa",
        "evidence": [
          {
            "view": "base",
            "kind": "chuan",
            "pos": "末传",
            "ref": "戌",
            "why": "末传戌为子息归着，古断谓末传子息又空"
          },
          {
            "view": "base",
            "kind": "xunkong",
            "ref": "戌",
            "why": "戌在旬空，古断以空论妻室子息之虑"
          },
          {
            "view": "base",
            "kind": "method",
            "ref": "比用",
            "why": "比用主事体相牵，故由功名牵及家室"
          }
        ],
        "ruleRef": "末传；旬空；课体",
        "note": "残篇末段 OCR 有缺，此链只据存文。",
        "role": "support"
      }
    ],
    "expect": {
      "kegs": [
        "辰/丙",
        "卯/辰",
        "丑/寅",
        "子/丑"
      ],
      "chuans": [
        "子",
        "亥",
        "戌"
      ],
      "chuanGz": [
        "戊子",
        "己亥",
        "戊戌"
      ],
      "xunkong": [
        "戌",
        "亥"
      ],
      "dayWangShuai": "旺",
      "monthZhi": "巳",
      "method": "比用",
      "zhonghuang": {
        "shiGan": "丁",
        "bianGan": "己",
        "bianGong": "酉",
        "bianLq": "子孙",
        "bianInChuan": ""
      }
    },
    "topics": [
      "终身",
      "省试",
      "己身"
    ]
  }
];
